/*
 * generated by Xtext
 */
package com.jda.webworks.config;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfigRuntimeModule extends com.jda.webworks.config.AbstractConfigRuntimeModule {

}
