/*
* generated by Xtext
*/
package com.jda.webworks.config.ui.contentassist;

import com.jda.webworks.config.ui.contentassist.AbstractConfigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ConfigProposalProvider extends AbstractConfigProposalProvider {

}
