/*
 * generated by Xtext
 */
package com.jda.webworks.config.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.ContentProposalLabelProvider;
import org.eclipse.xtext.ui.editor.outline.actions.IOutlineContribution;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import com.jda.webworks.config.ui.outline.CategoriesFilterOperationsContribution;
import com.jda.webworks.config.ui.outline.ConfigOutlineLabelProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfigUiModule extends
		com.jda.webworks.config.ui.AbstractConfigUiModule {
	public ConfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configureContentProposalLabelProvider(Binder binder) {
		binder.bind(ILabelProvider.class)
				.annotatedWith(ContentProposalLabelProvider.class)
				.to(ConfigOutlineLabelProvider.class);
	}
	
	public void configureFilterOperationsContribution(Binder binder) {
	    binder
	        .bind(IOutlineContribution.class).annotatedWith(
	            Names.named("FilterOperationsContribution"))
	        .to(CategoriesFilterOperationsContribution.class);
	}
}
